### ISSUE TITLE
Level 400 - no `shows.js` or `index.html` referred to

### ISSUE THREAD

**Issue by richardcrng** [WeAreAcademy/mark-react-proj--tv-shows#7]
I think Level 400 needs to be updated for a React and TS context (flagged to me by @AryaTandon and @kaliq-i).

It refers to the following:

> You can get the list of shows by loading `shows.js` in your `index.html` and using the provided function: `getAllShows()`

which I suspect is from the original history of this as a DOM project, but which no longer applies in this context.

In the absence of the API having a 'get all shows' endpoint, I suggested that an interim measure would be querying the API manually with ids 1-10 (or 1-20 or so) to discover the first 10-20 ids, to manually construct a list of shows.

**Comment by nbogie** [comment]
Thanks!  resolved.
